//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleApplication1.Model.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngay sinh can phai nam trong khoang do dai co dinh.
        /// </summary>
        internal static string ErrDT {
            get {
                return ResourceManager.GetString("ErrDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma can phai la so nguyen.
        /// </summary>
        internal static string ErrInt {
            get {
                return ResourceManager.GetString("ErrInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten can phai nam trong khoang do dai co dinh.
        /// </summary>
        internal static string ErrStr {
            get {
                return ResourceManager.GetString("ErrStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap Ma HS:.
        /// </summary>
        internal static string MsgMaHS {
            get {
                return ResourceManager.GetString("MsgMaHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap Ngay sinh:.
        /// </summary>
        internal static string MsgNgaysinh {
            get {
                return ResourceManager.GetString("MsgNgaysinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap Ten HS:.
        /// </summary>
        internal static string MsgTenHS {
            get {
                return ResourceManager.GetString("MsgTenHS", resourceCulture);
            }
        }
    }
}
